### PR TITLE
OpenCL Cost Model

### PR DESCRIPTION
**Pull request by gaohao95**
[Motivation of this PR](https://gitlab.tiker.net/inducer/boxtree/merge_requests/72).

TODO list:

* [x] Add `process_form_multipoles`.
* [x] Add `process_coarsen_multipoles`.
* [x] Add `process_refine_locals`.
* [x] Estimate calibration parameters (training).
* [x] Estimate the cost of new traversal (evaluating).
* [x] More sophisticated test cases.
* [x] Script for evaluating the cost model like `examples/cost.py` in pytential.
* [x] Write rst doc and register autodoc to it.
* [x] Move training/evaluating test case to example.
* [x] ~~Separate the collection of traversal parameters and predict timing. Add class `ParametrizedCosts` for generating actual timing from counter and calibration params.~~
* [x] Rename `CLFMMCostModel` to `FMMCostModel`

### CODE REVIEW

**Comment by gaohao95** [comment]
I'm no longer sure having a class `ParametrizedCosts` like currently in master branch is a good idea. `ParametrizedCosts` stores the "raw cost" and then predict the actual time based on the calibration parameter. Distributed load balancing requires predicting the time for each box, so we need to store O(N) data for each stage inside `ParametrizedCosts`, which consumes a lot of memory.

**Comment by inducer** [comment]
Thanks for your contribution! I've proposed some changes in https://github.com/gaohao95/boxtree/pull/1. If you like those, then this is ready to land.

**Comment by inducer** [comment]
This is ready to merge in my view. Since you spoke of additional changes in https://github.com/gaohao95/boxtree/pull/1, I'll hold off on merging. Ping me when done or if you've changed your mind.

**Comment by gaohao95** [comment]
@inducer I think this is ready to merge if CI passes.

**Comment by inducer** [comment]
Great! Thanks for your work on this. In it goes.

**Pull request merged**
