### PR TITLE
Rename `nterms` to `order` for the fmmlib wrangler

### PR DESCRIPTION
**Pull request by gaohao95**
As discussed in https://gitlab.tiker.net/inducer/boxtree/-/issues/25, `nterms` in fmmlib is a misnomer. This PR intends to change that to `order` to make it consistent with Sumpy's wrangler.

- [x] Mutually dependent on https://github.com/inducer/pytential/pull/153

### CODE REVIEW

**Comment by inducer** [comment]
This needs changes in pytential as well. Could you make a PR for those? I can help with the CI/merge orchestration then.

**Comment by gaohao95** [comment]
> This needs changes in pytential as well. Could you make a PR for those? I can help with the CI/merge orchestration then.

Sure! I'll work on that.

**Comment by gaohao95** [comment]
Could you give https://github.com/gaohao95/pytential/tree/rename-nterms a try?

**Comment by inducer** [comment]
Thanks!

**Pull request merged**
