### PR TITLE
tree_of_boxes: use make_mesh

### PR DESCRIPTION
**Pull request by alexfikl**
I think this is like the only place outside of `meshmode` that called the `Mesh()` constructor explicit. So problem solved forever! :heart:

### CODE REVIEW

**Comment by alexfikl** [comment]
```
WARNING: autodoc: failed to import module 'distributed' from module 'boxtree'; the following exception was raised:
libmpi.so.40: cannot open shared object file: No such file or directory
```
Hm, is conda in the middle of a rebuild or something? :\

**Comment by inducer** [comment]
I *think* I understand what's happening. Both pocl and openmpi depend on libhwloc, but pocl is stuck at an old version. When resolving dependencies for mpi4py, conda goes *aha*, I can install the ["external"](https://conda-forge.org/docs/user/tipsandtricks/#using-external-message-passing-interface-mpi-libraries) variety of OpenMPI and avoid this whole disaster.

Empirically, if `openmpi` is specified as an explicit dependency, it seems that conda will avoid installing the "external" variety.

**Comment by inducer** [comment]
#85 ought to help.

**Comment by inducer** [comment]
Thx!

**Pull request merged**
